config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'articles#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  get 'signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :body, presence: true, length: {minimum: 5, maximum: 10000}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles

  before_save {self.email = email.downcase}

  validates :username,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 105},
            format: {with: VALID_EMAIL_REGEX}

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def articles

  end

  def new
    # This is a note
    # This variable is a new line in the Articles table
    @article = Article.new
  end

  def edit
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    if @article.save
      # Example of flash message
      flash[:success] = "Thank you for your submission"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/brikd_controller.rb
class BrikdController < ApplicationController
  def blog
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brikd_helper.rb
module BrikdHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%# This is a comment, I'm adding to this comment -%>
<%# @articles is being called from articles_controller.rb where it links this variable to DB -%>

<%= render 'shared/errors', obj: @article %>

<%# This is the remaining bits of the form %>
<div class="row">
  <div class="col-xs-12">
    <%# form_for is a ruby plugin to assist with forms -%>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <%# This is the Title Bar -%>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :title %>
          </div>
          <div class="col-md-10">
            <%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %> </br>
          </div>
        </div>

        <%# This is the Body Paragraph Section -%>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :body %>
          </div>
          <div class="col-md-10">
            <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Body"  %> </br>
          </div>
        </div>

        <div class="form-group">
          <%# This is the Create Button -%>
          <div class="col-md-offset-2 col-md-8">
            <%= f.submit  class: 'btn btn-primary btn-lg' %>
          </div>
          <%# This is the Cancel Button that takes you home -%>
          <div class="col-md-2">
            <%= link_to 'Cancel', articles_path, class: "btn btn-primary btn-lg" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit your article</h1>

<%= render 'form' %>

app/views/articles/home.html.erb
<%# This is the giant title header that is listed on the main page %>
<div class="center jumbotron">
  <h1>Brikd.WTF_</h1>
  <%= link_to "Sign Up", "#", class: "btn btn-primary btn-lg btn-xlarge" %>
  <%= link_to "Sign In", "#", class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

<div class="col-xs-12">
  <iframe src="https://discordapp.com/widget?id=241226071297490944&theme=dark" width= 100%  height= "400" allowtransparency="true" frameborder="0"></iframe>
</div>

app/views/articles/index.html.erb
<%# This is the articles listed and body listed %>
<% @articles.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
            <%= truncate(article.body, length: 100) %>
            <div class="article-meta-details">
              <small>Created by: <%= article.user.username if article.user%>,
                <%= time_ago_in_words(article.created_at) %> ago,
                last updated: <%= time_ago_in_words(article.updated_at) %> ago </small>
            </div>
          </div>
          <div class="article-actions">
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete', article_path(article), method: :delete,
                        data: { confirm: "Are you sure you want to delete this?"},
                        class: "btn btn-xs btn-danger" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<%# This is what happens when you view an article -%>
<%# This will display the title, body and option you have for editing -%>
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.body) %>
  <div class="article-actions">
    <%= link_to 'Home', articles_path, class: "btn btn-xs btn-success" %>
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to 'Delete', article_path(@article), method: :delete,
                data: { confirm: "Are you sure you want to delete this?"},
                class: "btn btn-xs btn-danger" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      This all began thanks to the individuals of the discord server <a href="https://discord.gg/ZW6buAr">Brikd</a>
      by <a href="https://github.com/terminaltypist">TerminalTypist</a>
    </small>
    <ul>
      <li><%= link_to "Shit's Creek", root_path %></li>
    </ul>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<%# This flashes a message when you've added, deleted, updated. Example listed on articles_controller.rb -%>
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <%= link_to "Brikd", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li> -->
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Post/Read/Play<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Link</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <!-- <li></li> -->
        <li class="dropdown">
          <a href="#" class="mydrop" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color:#00FF00">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu mydrop2">
            <li><%= link_to "Articles", new_article_path, id: "mynavbardrop" %></li>
            <li><%= link_to "Forum", new_article_path, id: "mynavbardrop" %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<div class="container-fluid">
  <div class="row-fluid">
    <%= render 'layouts/navbar' %>
    <div class="container">
      <html>
        <head>
          <title>Brikd</title>
          <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
          <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
          <%= csrf_meta_tags %>
        </head>

        <body>
          <%= render 'layouts/messages' %>
          <div class = "container">
            <%= yield %>
          </div>
          <%= render 'layouts/footer' %>
        </body>
      </html>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<%# obj is a reference to whatever database object is being passed through wherever this partial is rendered -%>
<%# This displays any errors if there are any -%>
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              have stopped this article from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%# This is the remaining bits of the form %>
<div class="row">
  <div class="col-xs-12">
    <%# form_for is a ruby plugin to assist with forms -%>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

        <%# This is the Username -%>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :username %>
          </div>
          <div class="col-md-9">
            <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %> </br>
          </div>
        </div>

        <%# This is the Email -%>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :email %>
          </div>
          <div class="col-md-9">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter email"  %> </br>
          </div>
        </div>

        <%# This is the Password -%>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :password %>
          </div>
          <div class="col-md-9">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password"  %> </br>
          </div>
        </div>

        <div class="form-group">
          <%# This is the Create Button -%>
          <div class="col-md-offset-2 col-md-8">
            <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: 'btn btn-primary btn-lg') %>
          </div>
          <%# This is the Cancel Button that takes you home -%>
          <div class="col-md-2">
            <%= link_to 'Cancel', articles_path, class: "btn btn-primary btn-lg" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 align="center">New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">
  <strong>Typist:</strong>
  <%= @user.username %>
</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>